[package]
name = "temperatures"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
prometheus = "0.13"
prometheus-client = "0.22"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
